"""Database Agent - Creates schema, migrations, and seed data."""

from typing import Any

from agentsite.agents.base_agent import BaseAgent
from agentsite.agents.registry import AgentRegistry


@AgentRegistry.register
class DatabaseAgent(BaseAgent):
    """Produces SQLite schema, migrations, and synthetic seed data."""

    name = "DatabaseAgent"
    role = "Database Engineer"
    system_prompt = """You are an expert Database Engineer AI agent.
Your task is to create:
1. SQLite database schema with proper normalization
2. SQLAlchemy ORM models
3. Synthetic seed data (NO real personal information)
4. Migration scripts

Always use synthetic data only - fake names, fake companies, fake information.
Ensure proper indexing and foreign key relationships."""

    input_artifacts = ["01_prd.md", "05_api_spec.yaml"]
    output_artifacts = ["06_database_schema.sql"]
    allowed_tools = ["file_read", "file_write", "terminal"]
    validation_rules = [
        "Schema must include all required tables",
        "All tables must have primary keys",
        "Seed data must be synthetic only",
        "No hardcoded secrets",
    ]

    def execute(self, task_input: dict[str, Any]) -> dict[str, Any]:
        """Execute database design task."""
        # Generate database schema
        schema_content = self._generate_schema()
        schema_path = self.artifact_store.save("06_database_schema.sql", schema_content)

        # Generate SQLAlchemy models
        models_content = self._generate_models()
        models_path = self.artifact_store.save("models.py", models_content)

        # Generate seed data script
        seed_content = self._generate_seed_data()
        seed_path = self.artifact_store.save("seed_data.py", seed_content)

        return {
            "success": True,
            "artifacts": [schema_path, models_path, seed_path],
            "summary": "Generated database schema, models, and seed data",
        }

    def _generate_schema(self) -> str:
        """Generate SQL schema."""
        return """-- Database Schema for Employee Benefits Portal
-- Generated by AgentSite DatabaseAgent

-- Benefits table: stores information about available benefits
CREATE TABLE IF NOT EXISTS benefits (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    description TEXT NOT NULL,
    category TEXT NOT NULL,
    eligibility_requirements TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- FAQs table: stores frequently asked questions
CREATE TABLE IF NOT EXISTS faqs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    category TEXT NOT NULL,
    display_order INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Eligibility submissions: tracks eligibility check requests
CREATE TABLE IF NOT EXISTS eligibility_submissions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    employment_type TEXT NOT NULL,
    hours_per_week INTEGER NOT NULL,
    tenure_months INTEGER NOT NULL,
    is_eligible BOOLEAN NOT NULL,
    eligible_benefits TEXT,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Contact messages: stores support requests
CREATE TABLE IF NOT EXISTS contact_messages (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_benefits_category ON benefits(category);
CREATE INDEX IF NOT EXISTS idx_faqs_category ON faqs(category);
CREATE INDEX IF NOT EXISTS idx_contact_messages_created ON contact_messages(created_at);
"""

    def _generate_models(self) -> str:
        """Generate SQLAlchemy ORM models."""
        return """\"\"\"SQLAlchemy ORM models for Employee Benefits Portal.\"\"\"

from datetime import datetime
from sqlalchemy import Column, Integer, String, Boolean, Text, DateTime, ForeignKey
from sqlalchemy.orm import relationship, declarative_base

Base = declarative_base()


class Benefit(Base):
    \"\"\"Benefit model representing available employee benefits.\"\"\"
    
    __tablename__ = "benefits"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(200), nullable=False)
    description = Column(Text, nullable=False)
    category = Column(String(100), nullable=False)
    eligibility_requirements = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "category": self.category,
            "eligibility_requirements": self.eligibility_requirements,
        }


class FAQ(Base):
    \"\"\"FAQ model for frequently asked questions.\"\"\"
    
    __tablename__ = "faqs"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    question = Column(String(500), nullable=False)
    answer = Column(Text, nullable=False)
    category = Column(String(100), nullable=False)
    display_order = Column(Integer, default=0)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "question": self.question,
            "answer": self.answer,
            "category": self.category,
        }


class EligibilitySubmission(Base):
    \"\"\"Model for eligibility check submissions.\"\"\"
    
    __tablename__ = "eligibility_submissions"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    employment_type = Column(String(50), nullable=False)
    hours_per_week = Column(Integer, nullable=False)
    tenure_months = Column(Integer, nullable=False)
    is_eligible = Column(Boolean, nullable=False)
    eligible_benefits = Column(Text)
    submitted_at = Column(DateTime, default=datetime.utcnow)
    
    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "employment_type": self.employment_type,
            "hours_per_week": self.hours_per_week,
            "tenure_months": self.tenure_months,
            "is_eligible": self.is_eligible,
        }


class ContactMessage(Base):
    \"\"\"Model for contact/support messages.\"\"\"
    
    __tablename__ = "contact_messages"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String(200), nullable=False)
    email = Column(String(200), nullable=False)
    subject = Column(String(500), nullable=False)
    message = Column(Text, nullable=False)
    is_read = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    
    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "name": self.name,
            "email": self.email,
            "subject": self.subject,
            "message": self.message,
            "is_read": self.is_read,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }
"""

    def _generate_seed_data(self) -> str:
        """Generate synthetic seed data."""
        return """\"\"\"Seed data script for Employee Benefits Portal.
Uses SYNTHETIC DATA ONLY - no real personal information.\"\"\"

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from models import Base, Benefit, FAQ, EligibilitySubmission, ContactMessage

# Synthetic benefits data
BENEFITS_DATA = [
    {
        "name": "Health Insurance",
        "description": "Comprehensive medical coverage including doctor visits, hospital stays, and prescription drugs.",
        "category": "Medical",
        "eligibility_requirements": "Full-time employees (30+ hours/week) after 90 days",
    },
    {
        "name": "Dental Insurance",
        "description": "Preventive and basic dental care coverage with network dentists.",
        "category": "Medical",
        "eligibility_requirements": "All employees enrolled in health insurance",
    },
    {
        "name": "401(k) Retirement Plan",
        "description": "Tax-advantaged retirement savings with company match up to 4%.",
        "category": "Retirement",
        "eligibility_requirements": "All employees after 6 months of service",
    },
    {
        "name": "Paid Time Off",
        "description": "Generous PTO allowance starting at 15 days per year.",
        "category": "Time Off",
        "eligibility_requirements": "All full-time employees",
    },
    {
        "name": "Employee Assistance Program",
        "description": "Confidential counseling and support services for employees and family members.",
        "category": "Wellness",
        "eligibility_requirements": "All employees and immediate family",
    },
    {
        "name": "Professional Development",
        "description": "Annual stipend for courses, certifications, and conferences.",
        "category": "Career",
        "eligibility_requirements": "Full-time employees after 1 year",
    },
]

# Synthetic FAQ data
FAQS_DATA = [
    {
        "question": "How do I enroll in health insurance?",
        "answer": "New employees can enroll during their first 30 days or during open enrollment period (Nov 1 - Dec 15). Visit the HR portal or contact HR for assistance.",
        "category": "Enrollment",
    },
    {
        "question": "When does my coverage begin?",
        "answer": "Coverage begins on the first day of the month following your enrollment date. For new hires, this is typically your start date if you enroll within 30 days.",
        "category": "Coverage",
    },
    {
        "question": "Can I add my family to my plan?",
        "answer": "Yes! You can add your spouse and dependent children during open enrollment or within 30 days of a qualifying life event.",
        "category": "Coverage",
    },
    {
        "question": "How do I check my PTO balance?",
        "answer": "Log into the employee portal and navigate to 'My Time Off' to view your current balance and accrual history.",
        "category": "Time Off",
    },
    {
        "question": "What is the company match for 401(k)?",
        "answer": "The company matches 100% of your contributions up to 4% of your eligible compensation. You are eligible to participate after 6 months.",
        "category": "Retirement",
    },
]


def seed_database(db_url: str = "sqlite:///generated_app/database.db"):
    \"\"\"Populate database with synthetic seed data.\"\"\"
    engine = create_engine(db_url)
    Base.metadata.create_all(engine)
    
    SessionLocal = sessionmaker(bind=engine)
    db = SessionLocal()
    
    try:
        # Check if already seeded
        if db.query(Benefit).count() > 0:
            print("Database already seeded.")
            return
        
        # Insert benefits
        for benefit_data in BENEFITS_DATA:
            benefit = Benefit(**benefit_data)
            db.add(benefit)
        
        # Insert FAQs
        for i, faq_data in enumerate(FAQS_DATA):
            faq = FAQ(**faq_data, display_order=i)
            db.add(faq)
        
        db.commit()
        print(f"Seeded {len(BENEFITS_DATA)} benefits and {len(FAQS_DATA)} FAQs.")
        
    except Exception as e:
        db.rollback()
        print(f"Error seeding database: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed_database()
"""
